#!/usr/bin/env python

import os
import shutil
import subprocess

CACHE_DIR = "openbuddy"
MODEL_ID = "TheBloke/openbuddy-mistral-7B-v13-GPTQ"

if os.path.exists(CACHE_DIR):
    shutil.rmtree(CACHE_DIR)

os.makedirs(CACHE_DIR)

# Running system commands
# subprocess.run(['mkdir', 'openbuddy'], check=True)
# subprocess.run(['ls', '-l'], check=True)
os.environ['HF_HUB_ENABLE_HF_TRANSFER'] = '1'
subprocess.run(['huggingface-cli', 'download', 'TheBloke/openbuddy-mistral-7B-v13-GPTQ', '--local-dir', 'openbuddy', '--local-dir-use-symlinks', 'False'], check=True)

'''
    - mkdir openbuddy
    - ls -l
    - export HF_HUB_ENABLE_HF_TRANSFER=1
    - echo $HF_HUB_ENABLE_HF_TRANSFER
    - huggingface-cli download TheBloke/openbuddy-mistral-7B-v13-GPTQ --local-dir openbuddy --local-dir-use-symlinks False
'''